version: "3.8"

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: drupal
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  drupal:
    # image: drupal:9-apache
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./drupal9/web:/var/www/html

volumes:
  db_data:
